### ISSUE TITLE
EXCEPTION of type 'TypeError' occurred with message: 'plot() missing 1 required positional argument: 'rawdf'

### ISSUE THREAD

**Issue by rezakb** [teto/pymptcpanalyzer#28]
* mptcpanalyzer version (`$ mptcpanalyzer --version` or commit number): 0.3.2
* tshark version (`$ tshark --version`, must be >= 3.X.X): 3.0.3
* python version (`$ python --version`, must be >= 3.7): 3.7

Output of mptcpanalyzer -dDEBUG (or -dTRACE ):
```
	Problem when calling plotter.run
We passed the following arguments:
{}
{'plot_type': 'dss', 'out': None, 'display': False, 'title': None, 'primary': False, 'styles': [], 'dack': False, '__statement__': Statement(args='dss', raw='plot dss', command='plot', arg_list=['dss'], multiline_command='', terminator='', suffix='', pipe_to='', output='', output_to='')}
Traceback (most recent call last):
  File "/X/X/Library/Python/3.7/lib/python/site-packages/cmd2/cmd2.py", line 1753, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/X/X/Library/Python/3.7/lib/python/site-packages/cmd2/cmd2.py", line 2148, in onecmd
    stop = func(statement)
  File "/X/X/Library/Python/3.7/lib/python/site-packages/cmd2/cmd2.py", line 214, in cmd_wrapper
    return func(cmd2_app, args, unknown)
  File "/X/X/Library/Python/3.7/lib/python/site-packages/mptcpanalyzer/cli.py", line 1163, in do_plot
    raise e
  File "/X/X/Library/Python/3.7/lib/python/site-packages/mptcpanalyzer/cli.py", line 1157, in do_plot
    result = plotter.run(**dataframes, **dargs)
  File "/X/X/Library/Python/3.7/lib/python/site-packages/mptcpanalyzer/plot.py", line 268, in run
    fig = self.plot(*pargs, styles=styles, **kwargs)
TypeError: plot() missing 1 required positional argument: 'rawdf'
EXCEPTION of type 'TypeError' occurred with message: 'plot() missing 1 required positional argument: 'rawdf''``

# how to reproduce
run "plot dss"
Link to the pcap (if possible/relevant):

**Comment by teto** [comment]
Thanks for reporting. It's a plot I haven't updated. Will try to do soon and add it to the tests.
Meanwhile you can plot dss/dsn via `plot mptcp_attr examples/client_2_redundant.pcapng 0 dsn --display` with autocompletion, you can see available fields, for instance:
`dsn           dsnraw64      dss_dsn       dss_length    dss_rawack    dss_ssn `.
NB: Seems like the legend doesn't show the destination (client/server), gotta fix that too :/

**Comment by rezakb** [comment]
Thank you. I will try mptcp_attr.

**Comment by teto** [comment]
so this prove more complex than I had anticipated because I hadn't updated that code in a long time.
I have almost completed the update but I still have an issue: the plot is supposed to draw arrows from origin (sending time, data sequence number ) with size (0, dss.length) but matplotlib's autoscale doesn't work with arrows:
https://github.com/matplotlib/matplotlib/pull/13788

Apparently it's going to be fixed by september so I will release a fix with next matplotlib in september.
