### ISSUE TITLE
Crash trying to run the suggested example

### ISSUE THREAD

**Issue by tleonhardt** [teto/pymptcpanalyzer#8]
I tried running the suggested example on in the Readme.md "How to use" section: and it crashed.  I installed mptcpanalyzer using pip.

* mptcpanalyzer version ($ mptcpanalyzer --version):  0.2
* tshark version ($ tshark --version):  2.4.2
* python version:  3.6.3
* os version:  ubuntu 17.10

Output of **mptcpanalyzer --load examples/iperf-mptcp-0-0.pcap**:
```Bash
mptcpanalyzer.config:INFO: Configuration loaded from []
mptcpanalyzer:INFO: Starting in folder /home/todd/src/mptcpanalyzer
mptcpanalyzer:DEBUG: Pandas version: 0.21.0
toto:  (<mptcpanalyzer.tshark.TsharkConfig object at 0x7fd632e4c7f0>,)
mptcpanalyzer:INFO: Input file
mptcpanalyzer:INFO: Input file
mptcpanalyzer.data:DEBUG: Asked to load examples/iperf-mptcp-0-0.pcap
mptcpanalyzer.data:DEBUG: Asked to load examples/iperf-mptcp-0-0.pcap
An error happened :
sequence item 0: expected str instance, Field found
Displaying backtrace:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/cli.py", line 765, in main
    analyzer.do_load(cmd)
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/cli.py", line 529, in do_load
    self.load(args.input_file, args.regen)
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/cli.py", line 508, in load
    self.data = load_into_pandas(filename, self.tshark_config, regen)
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/data.py", line 103, in load_into_pandas
    config.hash()  # suffix
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/tshark.py", line 242, in hash
    options=self.options,
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/tshark.py", line 313, in generate_command
    fieldsExpanded=convert_field_list_into_tshark_str(fields_to_export),
  File "/usr/local/lib/python3.6/dist-packages/mptcpanalyzer-0.2-py3.6.egg/mptcpanalyzer/tshark.py", line 278, in convert_field_list_into_tshark_str
    return ' -e ' + ' -e '.join(fields)
TypeError: sequence item 0: expected str instance, Field found
```

Link to the incriminated pcap (if relevant):
https://github.com/teto/mptcpanalyzer/blob/master/examples/iperf-mptcp-0-0.pcap

**Comment by teto** [comment]
Thanks for reporting. Last commit on master `Sep 14, 2016` (and I knew it was kinda unstable so I hardly publicized it). Since then I've worked on and off on the new_plots branch but as it relies on wireshark extensions I've not had the time to merge yet, I never had the occasion to merge the fixes back. Part of my new job is to fix this so hopefully I can make another release soon.

**Comment by teto** [comment]
Also I would like to replace outdated tests with http://cmd2.readthedocs.io/en/latest/freefeatures.html#transcript-based-testing which look more robust

**Comment by teto** [comment]
this is fixed on master
