### ISSUE TITLE
had to manually create .cache folder for mptcpanalyzer

### ISSUE THREAD

**Issue by fciaccia** [teto/pymptcpanalyzer#9]
* mptcpanalyzer version ($ mptcpanalyzer --version): `log  mptcpanalyzer.cli 0.2`
* tshark version ($ tshark --version): 
```TShark (Wireshark) 2.2.6 (Git Rev Unknown from unknown)

Copyright 1998-2017 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, with POSIX capabilities (Linux), with libnl 3,
with GLib 2.50.3, with zlib 1.2.8, with SMI 0.4.8, with c-ares 1.12.0, with Lua
5.2.4, with GnuTLS 3.5.8, with Gcrypt 1.7.6-beta, with MIT Kerberos, with GeoIP,
with nghttp2 1.18.1.

Running on Linux 4.9.0-3-amd64, with locale C, with libpcap version 1.8.1, with
GnuTLS 3.5.8, with Gcrypt 1.7.6-beta, with zlib 1.2.8.
Intel Core Processor (Skylake) (with SSE4.2)

Built using gcc 6.3.0 20170516.
```

Output of mptcpanalyzer -ddd:

```log  mptcpanalyzer.cli
Configuration loaded from []
Config <mptcpanalyzer.config.MpTcpAnalyzerConfig object at 0x7f2f9f08efd0>
input= None
unknown= []
found extension EntryPoint.parse('xinterarrival = mptcpanalyzer.plots.dsn:CrossSubflowInterArrival')
found extension EntryPoint.parse('dss = mptcpanalyzer.plots.dsn:DSSOverTime')
found extension EntryPoint.parse('latency = mptcpanalyzer.plots.latency:LatencyHistogram')
found extension EntryPoint.parse('misc = mptcpanalyzer.plots.dsn:PerSubflowTimeVsX')
{'rwnd': True, 'dss_ssn': 'DSS Subflow Sequence Number', 'dsn': 'Data Sequence Number', 'dsnraw64': 'Raw Data Sequence Number', 'dss_rawack': 'DSS raw ack', 'dss_dsn': 'DSS Sequence Number', 'tcpseq': 'TCP sequence number', 'dack': 'MPTCP relative Ack', 'dss_length': 'DSS length', 'tcplen': 'TCP segment length'}
attributes= {'rwnd': True, 'dss_ssn': 'DSS Subflow Sequence Number', 'dsn': 'Data Sequence Number', 'dsnraw64': 'Raw Data Sequence Number', 'dss_rawack': 'DSS raw ack', 'dss_dsn': 'DSS Sequence Number', 'tcpseq': 'TCP sequence number', 'dack': 'MPTCP relative Ack', 'dss_length': 'DSS length', 'tcplen': 'TCP segment length'}
found extension EntryPoint.parse('ns3 = mptcpanalyzer.plots.ns3:PlotTraceSources')
found extension EntryPoint.parse('owd = mptcpanalyzer.plots.owd:OneWayDelay')
found extension EntryPoint.parse('interarrival = mptcpanalyzer.plots.dsn:InterArrivalTimes')
found extension EntryPoint.parse('dss_len = mptcpanalyzer.plots.dsn:DssLengthHistogram')
No matches
Interactive mode
<mptcpanalyzer.cli.MpTcpAnalyzer object at 0x7f2fab7e8e48>

        Welcome in mptcpanalyzer (http://github.com/lip6-mptcp/mptcpanalyzer)
        Press ? to get help

Ready>
```

Error found:

```exporter exited with code= 2
An error happened :
/bin/sh: 1: cannot create /home/user/.cache/mptcpanalyzer/%home%fciaccia%smb_tests%traces%trace.pcap.csv: Directory nonexistent

Displaying backtrace:

Traceback (most recent call last):
  File "/home/fciaccia/.local/lib/python3.5/site-packages/mptcpanalyzer/cli.py", line 659, in cli
    analyzer._load_data (args.input_file, args.regen)
  File "/home/fciaccia/.local/lib/python3.5/site-packages/mptcpanalyzer/cli.py", line 334, in _load_data
    self.data = self.load_into_pandas(filename, regen)
  File "/home/fciaccia/.local/lib/python3.5/site-packages/mptcpanalyzer/cli.py", line 480, in load_into_pandas
    csv_filename = self.get_matching_csv_filename(filename, regen)
  File "/home/fciaccia/.local/lib/python3.5/site-packages/mptcpanalyzer/cli.py", line 466, in get_matching_csv_filename
    raise Exception(stderr)
Exception: /bin/sh: 1: cannot create /home/fciaccia/.cache/mptcpanalyzer/%home%fciaccia%smb_tests%traces%trace.pcap.csv: Directory nonexistent

None
```

mptcpanalyzer installed following the install instructions in user .local folder. I had to manually create the /home/fciaccia/.cache/ folder to avoid the error. I do not believe the trace is relevant for the error.

**Comment by teto** [comment]
thanks for the report.
I've been working on this branch for the past year https://github.com/teto/mptcpanalyzer/tree/new_plots but it requires to compile wireshark with https://github.com/teto/wireshark/commits/reinject_stable.
I intend to do a stable release once I get my patches in upstream wireshark but I guess for now both branches are kinda broken sorry :/

**Comment by teto** [comment]
It should be fine on master. Feel free to reopen otherwise.
